client_config_backend: settings
client_config:
  client_id: 1080102325895-cutf71vs4fejjuisc1ql4b22ugauhjac.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install